//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEF.Services.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountExecutive
    {
        public long AccountExecutiveID { get; set; }
        public long EngagementID { get; set; }
        public long UserID { get; set; }
        public bool IsEngagementLead { get; set; }
        public bool CanEditPostVisit { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public long CreatedBy { get; set; }
        public long ModifiedBy { get; set; }
    
        public virtual Engagement Engagement { get; set; }
        public virtual User User { get; set; }
    }
}
