//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEF.Services.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionItem
    {
        public long ActionItemID { get; set; }
        public long EngagementID { get; set; }
        public string Description { get; set; }
        public long AssetID { get; set; }
        public long OwnerParticipantID { get; set; }
        public string Status { get; set; }
        public System.DateTime DueDate { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public long CreatedBy { get; set; }
        public long ModifiedBy { get; set; }
    
        public virtual Asset Asset { get; set; }
        public virtual Participant Participant { get; set; }
    }
}
