//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEF.Services.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        public Asset()
        {
            this.ActionItems = new HashSet<ActionItem>();
            this.ActivityAssets = new HashSet<ActivityAsset>();
            this.EngagementOutputs = new HashSet<EngagementOutput>();
            this.PackageAssets = new HashSet<PackageAsset>();
            this.PlaybookAssets = new HashSet<PlaybookAsset>();
        }
    
        public long AssetID { get; set; }
        public string Type { get; set; }
        public string Caption { get; set; }
        public string URL { get; set; }
        public byte[] File { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public long CreatedBy { get; set; }
        public long ModifiedBy { get; set; }
    
        public virtual ICollection<ActionItem> ActionItems { get; set; }
        public virtual ICollection<ActivityAsset> ActivityAssets { get; set; }
        public virtual ICollection<EngagementOutput> EngagementOutputs { get; set; }
        public virtual ICollection<PackageAsset> PackageAssets { get; set; }
        public virtual ICollection<PlaybookAsset> PlaybookAssets { get; set; }
    }
}
