//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEF.Services.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Engagement
    {
        public Engagement()
        {
            this.AccountExecutives = new HashSet<AccountExecutive>();
            this.EngagementOutputs = new HashSet<EngagementOutput>();
            this.Playbooks = new HashSet<Playbook>();
            this.PlaybookSurveys = new HashSet<PlaybookSurvey>();
        }
    
        public long EngagementID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<byte> Duration { get; set; }
        public Nullable<long> AssineeUserID { get; set; }
        public string EngagementType { get; set; }
        public string EngagementStatus { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public long CreatedBy { get; set; }
        public long ModifiedBy { get; set; }
    
        public virtual ICollection<AccountExecutive> AccountExecutives { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<EngagementOutput> EngagementOutputs { get; set; }
        public virtual ICollection<Playbook> Playbooks { get; set; }
        public virtual ICollection<PlaybookSurvey> PlaybookSurveys { get; set; }
    }
}
