//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEF.Services.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EquusEntities : DbContext
    {
        public EquusEntities()
            : base("name=EquusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountExecutive> AccountExecutives { get; set; }
        public virtual DbSet<ActionItem> ActionItems { get; set; }
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<ActivityAsset> ActivityAssets { get; set; }
        public virtual DbSet<ActivityBenefit> ActivityBenefits { get; set; }
        public virtual DbSet<ActivityDependency> ActivityDependencies { get; set; }
        public virtual DbSet<ActivityIndustry> ActivityIndustries { get; set; }
        public virtual DbSet<ActivityInternalResource> ActivityInternalResources { get; set; }
        public virtual DbSet<ActivityNextStep> ActivityNextSteps { get; set; }
        public virtual DbSet<ActivityTip> ActivityTips { get; set; }
        public virtual DbSet<ActivityVisitorResource> ActivityVisitorResources { get; set; }
        public virtual DbSet<Asset> Assets { get; set; }
        public virtual DbSet<BriefingRequest> BriefingRequests { get; set; }
        public virtual DbSet<Engagement> Engagements { get; set; }
        public virtual DbSet<EngagementOutput> EngagementOutputs { get; set; }
        public virtual DbSet<Industry> Industries { get; set; }
        public virtual DbSet<Package> Packages { get; set; }
        public virtual DbSet<PackageActivity> PackageActivities { get; set; }
        public virtual DbSet<PackageAsset> PackageAssets { get; set; }
        public virtual DbSet<PackageBenefit> PackageBenefits { get; set; }
        public virtual DbSet<PackageIndustry> PackageIndustries { get; set; }
        public virtual DbSet<PackageInput> PackageInputs { get; set; }
        public virtual DbSet<PackageInternalResource> PackageInternalResources { get; set; }
        public virtual DbSet<PackageNextStep> PackageNextSteps { get; set; }
        public virtual DbSet<PackageOutput> PackageOutputs { get; set; }
        public virtual DbSet<PackagePrerequisite> PackagePrerequisites { get; set; }
        public virtual DbSet<PackageSurveyQuestion> PackageSurveyQuestions { get; set; }
        public virtual DbSet<PackageTip> PackageTips { get; set; }
        public virtual DbSet<PackageTopic> PackageTopics { get; set; }
        public virtual DbSet<PackageVisitorResource> PackageVisitorResources { get; set; }
        public virtual DbSet<Participant> Participants { get; set; }
        public virtual DbSet<Playbook> Playbooks { get; set; }
        public virtual DbSet<PlaybookAsset> PlaybookAssets { get; set; }
        public virtual DbSet<PlaybookPackage> PlaybookPackages { get; set; }
        public virtual DbSet<PlaybookSurvey> PlaybookSurveys { get; set; }
        public virtual DbSet<PlaybookSurveyAnswer> PlaybookSurveyAnswers { get; set; }
        public virtual DbSet<PlaybookSurveyTopic> PlaybookSurveyTopics { get; set; }
        public virtual DbSet<SurveyAnswerOption> SurveyAnswerOptions { get; set; }
        public virtual DbSet<SurveyQuestion> SurveyQuestions { get; set; }
        public virtual DbSet<Topic> Topics { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Visit> Visits { get; set; }
        public virtual DbSet<Visitor> Visitors { get; set; }
    }
}
