//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEF.Services.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public Package()
        {
            this.PackageActivities = new HashSet<PackageActivity>();
            this.PackageAssets = new HashSet<PackageAsset>();
            this.PackageBenefits = new HashSet<PackageBenefit>();
            this.PackageIndustries = new HashSet<PackageIndustry>();
            this.PackageInputs = new HashSet<PackageInput>();
            this.PackageInternalResources = new HashSet<PackageInternalResource>();
            this.PackageNextSteps = new HashSet<PackageNextStep>();
            this.PackageOutputs = new HashSet<PackageOutput>();
            this.PackagePrerequisites = new HashSet<PackagePrerequisite>();
            this.PackageSurveyQuestions = new HashSet<PackageSurveyQuestion>();
            this.PackageTips = new HashSet<PackageTip>();
            this.PackageTopics = new HashSet<PackageTopic>();
            this.PackageVisitorResources = new HashSet<PackageVisitorResource>();
            this.Package1 = new HashSet<Package>();
            this.PlaybookPackages = new HashSet<PlaybookPackage>();
        }
    
        public long PackageID { get; set; }
        public long ParentPackageID { get; set; }
        public string PackageName { get; set; }
        public string VersionName { get; set; }
        public string Description { get; set; }
        public string Details { get; set; }
        public Nullable<decimal> MaxCost { get; set; }
        public Nullable<decimal> MinCost { get; set; }
        public Nullable<decimal> MaxPrice { get; set; }
        public Nullable<decimal> MinPrice { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public long CreatedBy { get; set; }
        public long ModifiedBy { get; set; }
    
        public virtual ICollection<PackageActivity> PackageActivities { get; set; }
        public virtual ICollection<PackageAsset> PackageAssets { get; set; }
        public virtual ICollection<PackageBenefit> PackageBenefits { get; set; }
        public virtual ICollection<PackageIndustry> PackageIndustries { get; set; }
        public virtual ICollection<PackageInput> PackageInputs { get; set; }
        public virtual ICollection<PackageInternalResource> PackageInternalResources { get; set; }
        public virtual ICollection<PackageNextStep> PackageNextSteps { get; set; }
        public virtual ICollection<PackageOutput> PackageOutputs { get; set; }
        public virtual ICollection<PackagePrerequisite> PackagePrerequisites { get; set; }
        public virtual ICollection<PackageSurveyQuestion> PackageSurveyQuestions { get; set; }
        public virtual ICollection<PackageTip> PackageTips { get; set; }
        public virtual ICollection<PackageTopic> PackageTopics { get; set; }
        public virtual ICollection<PackageVisitorResource> PackageVisitorResources { get; set; }
        public virtual ICollection<Package> Package1 { get; set; }
        public virtual Package Package2 { get; set; }
        public virtual ICollection<PlaybookPackage> PlaybookPackages { get; set; }
    }
}
