//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEF.Services.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaybookSurveyAnswer
    {
        public long PlaybookSurveyAnswerID { get; set; }
        public long PlaybookSurveyID { get; set; }
        public long SurveyAnswerOptionID { get; set; }
        public string AnswerText { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public long CreatedBy { get; set; }
        public long ModifiedBy { get; set; }
    
        public virtual PlaybookSurvey PlaybookSurvey { get; set; }
        public virtual SurveyAnswerOption SurveyAnswerOption { get; set; }
    }
}
