//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEF.Services.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Playbook
    {
        public Playbook()
        {
            this.Participants = new HashSet<Participant>();
            this.PlaybookAssets = new HashSet<PlaybookAsset>();
            this.PlaybookPackages = new HashSet<PlaybookPackage>();
        }
    
        public long PlaybookID { get; set; }
        public long EngagementID { get; set; }
        public string Status { get; set; }
        public string Title { get; set; }
        public string Overview { get; set; }
        public Nullable<short> Duration { get; set; }
        public decimal Price { get; set; }
        public string Details { get; set; }
        public Nullable<long> TemplateID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public long CreatedBy { get; set; }
        public long ModifiedBy { get; set; }
    
        public virtual Engagement Engagement { get; set; }
        public virtual ICollection<Participant> Participants { get; set; }
        public virtual ICollection<PlaybookAsset> PlaybookAssets { get; set; }
        public virtual ICollection<PlaybookPackage> PlaybookPackages { get; set; }
    }
}
