//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEF.Services.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        public Topic()
        {
            this.PackageTopics = new HashSet<PackageTopic>();
            this.PlaybookSurveyTopics = new HashSet<PlaybookSurveyTopic>();
        }
    
        public short TopicID { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte[] Icon { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public long CreatedBy { get; set; }
        public long ModifiedBy { get; set; }
    
        public virtual ICollection<PackageTopic> PackageTopics { get; set; }
        public virtual ICollection<PlaybookSurveyTopic> PlaybookSurveyTopics { get; set; }
    }
}
