//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEF.Services.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitor
    {
        public Visitor()
        {
            this.Participants = new HashSet<Participant>();
            this.Visits = new HashSet<Visit>();
        }
    
        public long VisitorID { get; set; }
        public long UserID { get; set; }
        public string Type { get; set; }
        public string Organization { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public long CreatedBy { get; set; }
        public long ModifiedBy { get; set; }
    
        public virtual ICollection<Participant> Participants { get; set; }
        public virtual ICollection<Visit> Visits { get; set; }
    }
}
